version: '3'

services:
    osdr-jmol-imaging-service:
        restart: always
        container_name: osdr-jmol-imaging-service
        image: docker.your-company.com/sds/osdr-jmol-imaging-service:latest
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temp
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        build:
            context: .
        volumes:
        - /home/logs:/logs/
        - /home/temp:/temp/
        networks:
        - osdr-net-ext
            
networks:
    osdr-net-ext:
        external:
            name: osdr-sys-net
